In [1]:
import pandas as pd
df = pd.read_csv('allteams-nice-NI.csv')
df

,id,puzzle-games,puzzle-rating,puzzle-rd,blitz-games,blitz-rating,blitz-rd,rapid-games,rapid-rating,rapid-rd,storm-runs,storm-score
0,vay_vision,2.0,1846.0,246.0,2087,1785,49,160,2041,67,NaN,NaN
1,ian_fidelino,326.0,2447.0,146.0,1282,2297,45,164,2332,55,1.0,35.0
2,bltsandwich64,228.0,1949.0,190.0,92,1439,59,62,1640,75,NaN,NaN
3,rchoi2010,NaN,NaN,NaN,2,1145,227,0,1500,500,NaN,NaN
4,furyempire,49.0,1425.0,80.0,4,1724,170,6,1568,145,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
205121,dustin1304,2243.0,1535.0,61.0,33,905,100,229,1320,46,30.0,20.0
205122,waschbaer231,270.0,2190.0,197.0,724,2321,87,60,2152,93,NaN,NaN
205123,jewelz83,77.0,2184.0,198.0,46,1693,85,2,1642,253,NaN,NaN
205124,klonkrieger,52.0,1743.0,87.0,2525,1971,45,8,1686,168,NaN,NaN
205125,thebiggreek,560.0,2634.0,95.0,1727,2561,45,254,2500,53,742.0,75.0

In [20]:
df_nona = df.dropna()
prune = df_nona[(df_nona['blitz-rd']<100)&(df_nona['puzzle-rd']<100)&
                        (df_nona['rapid-rd']<100)&(df_nona['storm-runs']>10)]
prune

,id,puzzle-games,puzzle-rating,puzzle-rd,blitz-games,blitz-rating,blitz-rd,rapid-games,rapid-rating,rapid-rd,storm-runs,storm-score
7,bumblezz,1007.0,1907.0,61.0,110,1254,45,419,1289,46,60.0,24.0
14,coymagician171,1804.0,1705.0,76.0,106,1199,46,392,1297,52,15.0,17.0
16,sohil_526,3289.0,1511.0,63.0,411,1090,48,533,1213,46,30.0,24.0
20,sadecedenedim,44.0,2206.0,90.0,27,1620,88,24,2103,86,30.0,39.0
32,windrose11,2790.0,1752.0,74.0,2523,1502,45,439,1585,47,99.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
205093,leopold2003,698.0,2038.0,61.0,530,1687,45,201,1789,59,49.0,31.0
205094,masterion2,11209.0,2036.0,64.0,1386,1771,46,348,1927,53,140.0,46.0
205095,lordnyrob,3580.0,2391.0,63.0,531,1789,48,102,1823,52,617.0,45.0
205117,voechr,4553.0,2180.0,66.0,3567,1973,45,72,2115,66,141.0,51.0
205125,thebiggreek,560.0,2634.0,95.0,1727,2561,45,254,2500,53,742.0,75.0

In [21]:
qprune = prune[['puzzle-rating','rapid-rating','blitz-rating','storm-score']]
qprune.columns = ['puzzle','rapid','blitz','storm']
qprune

        puzzle  rapid  blitz  storm
7       1907.0   1289   1254   24.0
14      1705.0   1297   1199   17.0
16      1511.0   1213   1090   24.0
20      2206.0   2103   1620   39.0
32      1752.0   1585   1502   36.0
...        ...    ...    ...    ...
205093  2038.0   1789   1687   31.0
205094  2036.0   1927   1771   46.0
205095  2391.0   1823   1789   45.0
205117  2180.0   2115   1973   51.0
205125  2634.0   2500   2561   75.0

[15500 rows x 4 columns]

In [30]:
import statsmodels.formula.api as smf
qmod = smf.quantreg('blitz ~ storm + puzzle', qprune)
res = qmod.fit(q=.5)
print(res.summary())

                         QuantReg Regression Results
==============================================================================
Dep. Variable:                  blitz   Pseudo R-squared:               0.5244
Model:                       QuantReg   Bandwidth:                       32.68
Method:                 Least Squares   Sparsity:                        424.9
Date:                Tue, 30 Mar 2021   No. Observations:                15500
Time:                        13:07:34   Df Residuals:                    15497
                                        Df Model:                            2
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    194.2253     12.725     15.263      0.000     169.282     219.168
storm         16.3832      0.186     88.226      0.000      16.019      16.747
puzzle         0.4519      0.008     56.219      0.000       0.436       0.468
==============================================================================

The condition number is large, 1.53e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [31]:
import numpy as np
quantiles = np.arange(0.1,1,0.1)
print(quantiles)
models = []
params = []

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

In [32]:
for qt in quantiles:
    print(qt)
    res = qmod.fit(q = qt )
    models.append(res)
    params.append([qt, res.params['Intercept'], res.params['storm'],res.params['puzzle']] 
                  + res.conf_int().loc['storm'].tolist() + res.conf_int().loc['puzzle'].tolist())

0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7000000000000001
0.8

C:\Users\Akul Bector\Anaconda3\envs\py37\lib\site-packages\statsmodels\regression\quantile_regression.py:191: IterationLimitWarning: Maximum number of iterations (1000) reached.
  ") reached.", IterationLimitWarning)

0.9

In [33]:
params = pd.DataFrame(data = params, columns = ['qt','intercept','storm_coef','puzzle_coef'
                                                ,'scf_lower_bound','scf_upper_bound'
                                               ,'pcf_lower_bound','pcf_upper_bound'])

params

,qt,intercept,storm_coef,puzzle_coef,scf_lower_bound,scf_upper_bound,pcf_lower_bound,pcf_upper_bound
0,0.1,22.712105,17.817275,0.401293,17.149098,18.485453,0.374420,0.428165
1,0.2,81.352587,17.713339,0.411857,17.221158,18.205520,0.391679,0.432036
2,0.3,124.855876,17.210013,0.427009,16.782067,17.637959,0.409184,0.444834
3,0.4,158.645875,16.756649,0.441736,16.380811,17.132486,0.425776,0.457695
4,0.5,194.225300,16.383230,0.451914,16.019242,16.747218,0.436158,0.467670
5,0.6,227.091933,16.015120,0.463256,15.681725,16.348514,0.448534,0.477978
6,0.7,275.052400,15.448024,0.471649,15.101390,15.794659,0.456032,0.487267
7,0.8,335.672682,14.973759,0.476648,14.598978,15.348539,0.459347,0.493950
8,0.9,465.236189,14.363549,0.459464,13.891067,14.836030,0.436838,0.482091

In [34]:
params.to_csv('BlitzQuantReg-10r-planes.csv')

In [26]:
qmod = smf.quantreg('rapid ~ storm + puzzle', qprune)
res = qmod.fit(q=.5)
print(res.summary())

                         QuantReg Regression Results
==============================================================================
Dep. Variable:                  rapid   Pseudo R-squared:               0.4818
Model:                       QuantReg   Bandwidth:                       30.89
Method:                 Least Squares   Sparsity:                        400.4
Date:                Tue, 30 Mar 2021   No. Observations:                15500
Time:                        13:06:16   Df Residuals:                    15497
                                        Df Model:                            2
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    341.2709     11.991     28.461      0.000     317.768     364.774
storm         11.0559      0.175     63.184      0.000      10.713      11.399
puzzle         0.5236      0.008     69.124      0.000       0.509       0.538
==============================================================================

The condition number is large, 1.53e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [27]:
quantiles = np.arange(0.1,1,0.1)
print(quantiles)
models = []
params = []
for qt in quantiles:
    print(qt)
    res = qmod.fit(q = qt )
    models.append(res)
    params.append([qt, res.params['Intercept'], res.params['storm'],res.params['puzzle']] 
                  + res.conf_int().loc['storm'].tolist() + res.conf_int().loc['puzzle'].tolist())

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7000000000000001
0.8
0.9

In [28]:
params = pd.DataFrame(data = params, columns = ['qt','intercept','storm_coef','puzzle_coef'
                                                ,'scf_lower_bound','scf_upper_bound'
                                               ,'pcf_lower_bound','pcf_upper_bound'])

params

,qt,intercept,storm_coef,puzzle_coef,scf_lower_bound,scf_upper_bound,pcf_lower_bound,pcf_upper_bound
0,0.1,152.861451,11.611737,0.499285,10.881555,12.341919,0.468934,0.529635
1,0.2,211.318426,11.431127,0.513417,10.950372,11.911882,0.493418,0.533416
2,0.3,270.836756,11.415395,0.510285,11.008004,11.822786,0.493073,0.527498
3,0.4,298.307375,11.292008,0.519980,10.937297,11.646719,0.504795,0.535164
4,0.5,341.270944,11.055926,0.523581,10.712947,11.398905,0.508734,0.538427
5,0.6,385.086165,10.812218,0.525831,10.491958,11.132479,0.511799,0.539862
6,0.7,425.915200,10.589333,0.530400,10.263611,10.915055,0.515871,0.544929
7,0.8,496.991953,10.228169,0.525553,9.871972,10.584366,0.509476,0.541631
8,0.9,602.307783,10.069686,0.509872,9.613206,10.526167,0.488816,0.530928

In [29]:
params.to_csv('RapidQuantReg-10r-planes.csv')